[workspace]
resolver = "3"
members = [
    "crates/*"
]
default-members = [
    "crates/*"
]

[workspace.package]
description = "Toby's little library of custom stuff"
version = "0.0.1"
edition = "2024"
rust-version = "1.96.0"

license = "MIT"
repository = "https://github.com/tobiO0310/tobys_lib"
keywords = ["little", "library"]
categories = ["library"]

[workspace.dependencies]

tobys-lib-macros = { path = "crates/tobys_lib_macros", version = "0.0" }

proc-macro2 = { version = "1.0.107", default-features = false }
quote = { version = "1.0.47", default-features = false }
syn = { version = "3.0.3", features = ["full"] }
trybuild = { version = "1.0.120" }

[profile.release]
lto = true

[workspace.lints.rust]
elided_lifetimes_in_paths = "warn"
future_incompatible = { level = "warn", priority = -1 }
nonstandard_style = { level = "warn", priority = -1 }
rust_2018_idioms = { level = "warn", priority = -1 }
rust_2021_prelude_collisions = "warn"
semicolon_in_expressions_from_macros = "warn"
trivial_numeric_casts = "warn"
unexpected_cfgs = "warn"

unused_qualifications = "warn"

[workspace.lints.rustdoc]
all = "warn"
missing_crate_level_docs = "warn"
broken_intra_doc_links = "deny"

[workspace.lints.clippy]
pedantic = "warn"
absolute_paths = "warn"

arithmetic_side_effects = "warn"
undocumented_unsafe_blocks = "warn"
ptr_as_ptr = "warn"
cast_possible_truncation = "warn"
cast_sign_loss = "warn"
cast_possible_wrap = "warn"
exit = "warn"
tests_outside_test_module = "warn"
assertions_on_result_states = "warn"
error_impl_error = "warn"
or_fun_call = "warn"
