[package]
name = "tobys-lib"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
tobys-lib-core = { workspace = true }
tobys-lib-macros = { workspace = true, optional = true }

num-bigint = { workspace = true, optional = true }
num-traits = { workspace = true }
rand = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }

[dev-dependencies]

rand = { workspace = true, features = ["default"] }

[features]
full = [
    "bigint",
    "cron",
    "macros",
    "rand",
    "rayon",
    "std",
    "tobys-lib-core/full",
    "tobys-lib-macros/full"
]
default = ["std"]
alloc = ["rand?/alloc", "tobys-lib-core/alloc"]
std = ["rand?/std", "num-bigint?/std", "tobys-lib-core/std"]

bigint = ["dep:num-bigint", "alloc"]
cron = ["tobys-lib-core/cron", "tobys-lib-macros?/cron"]
macros = ["dep:tobys-lib-macros"]
rand = ["dep:rand", "num-bigint?/rand_0_10"]
rayon = ["dep:rayon", "std"]

# docs.rs-specific configuration
[package.metadata.docs.rs]
# document all features
all-features = true
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
